name: Action To Get Commits.py
run-name: ${{ github.actor }} Run of Get Commit Messages
on: [pull_request]
#Variables that can be changed by the user
env:
  sourcePath: /requirements
  targetList: /Code/Backend/changed-file-list.txt
  outputFile: /Code/Backend/Traceability_Report.txt
  targetThreshold: 0.0
  devFeedback: |
    '{"est_ossl_util.c RQ4.txt": 21.0}'
jobs:
  Example-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
    # grab default branch to calculate branch point to know when to stop linting
      - run: |
          cd ./Code/Backend
          touch Commits_Report.txt
          git log >> Commits_Report.txt

      - name: Print Variables
        run: |
          echo "GITHUB_WORKFLOW:$GITHUB_WORKFLOW"
          echo "GITHUB_EVENT_NAME:$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
          echo "GITHUB_SHA:$GITHUB_SHA"
          echo "GITHUB_REF:$GITHUB_REF"
          echo "GITHUB_HEAD_REF:$GITHUB_HEAD_REF"
      #git checkout $GITHUB_HEAD_REF

      - name: Upload changed files list
        uses: actions/upload-artifact@v3
        with:
          name: Commit Report
          path: Code/Backend/Commits_Report.txt
